server:
  port: 8070
spring:
  application:
    name: eurekaserver
  zipkin:
    base-url: http://zipkin:9411/
  cloud:
    loadbalancer:
      ribbot:
        enabled: false
management:
  tracing:
    sampling:
      probability: 1


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-uri:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka